### ISSUE TITLE
Meta task - things not done in the spec, and where they are being handled

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#64]
This is just one place to list any issues with the spec that haven't been implemented yet, rather than listing in a protocol doc that could be public soon.

- See also #63 (Minor discrepancies
- [x] status/scan 403 Requests should specific nnn bits - see #34 
- [x] status/scan 403 Location request too big - see #65
- [x] status/send handling other fields in the "contacts" - see #66
- [ ] status/send response content, it would be the start of the healthcare provider integration - see #56 
- [ ] /sync reject unknown servers - see #67
- [x] Handle appropritely sized geo points - e.g. 4DP store, 2DP retrieve - see #68

**Comment by mitra42** [comment]
I think we can close this now as everything has an issue, and the list of open issues is a better TODO list than this
